-- Auto-generated by cellphones_full_ecommerce_pipeline.py
-- Source: https://cellphones.com.vn
-- Generated at: 2026-03-29 11:43:10
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- users: 20 rows
INSERT INTO users (id, username, email, password, first_name, last_name, phone, avt_url, role, status, verified, last_login, created_at, updated_at) VALUES
(1, 'customer_0001', 'customer_0001@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User1', 'Demo', '0900000001', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-07-05 10:09:11', '2026-03-29 11:43:10'),
(2, 'customer_0002', 'customer_0002@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User2', 'Demo', '0900000002', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2025-07-02 21:57:19', '2026-03-29 11:43:10'),
(3, 'customer_0003', 'customer_0003@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User3', 'Demo', '0900000003', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2025-04-21 09:01:07', '2026-03-29 11:43:10'),
(4, 'customer_0004', 'customer_0004@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User4', 'Demo', '0900000004', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2025-03-07 00:33:22', '2026-03-29 11:43:10'),
(5, 'customer_0005', 'customer_0005@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User5', 'Demo', '0900000005', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-08-17 02:44:58', '2026-03-29 11:43:10'),
(6, 'customer_0006', 'customer_0006@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User6', 'Demo', '0900000006', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2025-12-19 14:27:28', '2026-03-29 11:43:10'),
(7, 'customer_0007', 'customer_0007@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User7', 'Demo', '0900000007', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-09-14 17:55:38', '2026-03-29 11:43:10'),
(8, 'customer_0008', 'customer_0008@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User8', 'Demo', '0900000008', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2025-03-14 09:41:03', '2026-03-29 11:43:10'),
(9, 'customer_0009', 'customer_0009@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User9', 'Demo', '0900000009', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-04-09 02:37:02', '2026-03-29 11:43:10'),
(10, 'customer_0010', 'customer_0010@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User10', 'Demo', '0900000010', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-04-03 10:28:24', '2026-03-29 11:43:10'),
(11, 'customer_0011', 'customer_0011@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User11', 'Demo', '0900000011', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2026-02-01 05:11:35', '2026-03-29 11:43:10'),
(12, 'customer_0012', 'customer_0012@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User12', 'Demo', '0900000012', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-10-26 11:27:46', '2026-03-29 11:43:10'),
(13, 'customer_0013', 'customer_0013@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User13', 'Demo', '0900000013', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-07-09 05:00:37', '2026-03-29 11:43:10'),
(14, 'customer_0014', 'customer_0014@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User14', 'Demo', '0900000014', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2026-02-01 12:16:13', '2026-03-29 11:43:10'),
(15, 'customer_0015', 'customer_0015@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User15', 'Demo', '0900000015', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2025-12-27 16:12:01', '2026-03-29 11:43:10'),
(16, 'customer_0016', 'customer_0016@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User16', 'Demo', '0900000016', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-09-27 00:42:08', '2026-03-29 11:43:10'),
(17, 'customer_0017', 'customer_0017@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User17', 'Demo', '0900000017', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2026-03-07 07:11:29', '2026-03-29 11:43:10'),
(18, 'customer_0018', 'customer_0018@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User18', 'Demo', '0900000018', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-07-15 02:26:53', '2026-03-29 11:43:10'),
(19, 'customer_0019', 'customer_0019@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User19', 'Demo', '0900000019', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2024-06-30 07:15:40', '2026-03-29 11:43:10'),
(20, 'customer_0020', 'customer_0020@example.com', '$2b$12$abcdefghijklmnopqrstuv1234567890abcdefghi', 'User20', 'Demo', '0900000020', '', 'CUSTOMER', 'ACTIVE', 1, '2026-03-29 11:43:10', '2025-06-05 06:25:13', '2026-03-29 11:43:10');

-- products: 2 rows
INSERT INTO products (id, name, description, detail, summary, category, price, brand, promotion, quantity, view, created_at, updated_at) VALUES
(1, 'HONOR X8d 8GB 128GB - Đã kích hoạt', 'Mua điện thoại HONOR X8d 8GB 128GB đã kích hoạt bảo hành, đổi mới 30 ngày, có trả góp 0%', '- Kích thước màn hình: 6.77 inches
- Công nghệ màn hình: AMOLED
- Camera sau: Camera chính 108MP (f/1.75) + Camera rộng 5MP (f/2.2)
- Camera trước: 16MP (f/2.45)
- Chipset: Snapdragon 6s 4G thế hệ 2
- Công nghệ NFC: Có
- Dung lượng RAM: 8 GB
- Bộ nhớ trong: 128 GB
- Pin: 6800mAh (giá trị định mức), 7000 mAh (giá trị điển hình)
- Thẻ SIM: 2 Nano-SIM
- Hệ điều hành: MagicOS 10 (Dựa trên Android 16)
- Độ phân giải màn hình: 1080 x 2392 pixels
- Tính năng màn hình: Màu sắc: 1,07 tỷ màuCông nghệ Eye Comfort800 nit (điển hình) 1300 nit (loại HBM) 3000 nit (loại APL)Chất liệu kính Thủy tinh Aluminosilicate
- Loại CPU: Octa-core, 4 * A73 2,9 GHz + 4 * A53 1,9 GHz', 'Mua điện thoại HONOR X8d 8GB 128GB đã kích hoạt bảo hành, đổi mới 30 ngày, có trả góp 0%', 'Điện thoại', 6290000, 'HONOR', 2, 46, 0, '2026-02-23 12:27:29', '2026-03-29 11:43:10'),
(2, 'POCO X8 Pro Max 5G 12GB 256GB - Đã kích hoạt', 'Mua điện thoại Poco X8 Pro Max 12GB/256GB đã kích hoạt bảo hành, đổi mới 30 ngày, có trả góp 0%', '- Kích thước màn hình: 6.83 inches
- Công nghệ màn hình: AMOLED
- Camera sau: 50 MP f/1.5 (cảm biến Light Hunter 600, OIS) + 8 MP (góc siêu rộng)
- Camera trước: 20 MP
- Chipset: MediaTek Dimensity 9500s
- Dung lượng RAM: 12 GB
- Bộ nhớ trong: 256 GB
- Pin: 8.500 mAh
- Thẻ SIM: Dual nano-SIM hoặc 1 nano-SIM + 1 eSIM
- Hệ điều hành: Xiaomi HyperOS 3 (Android 16)
- Độ phân giải màn hình: 2772 x 1280 pixels
- Tính năng màn hình: Độ sáng tối đa 3.500 nits, PWM 3840Hz, 68 tỷ màu, dải màu DCI-P3, HDR10+
- Loại CPU: 1 × Cortex-X925 (tối đa 3.73GHz) + 3 × Cortex-X4 (tối đa 3.3GHz) + 4 × Cortex-A720 (tối đa 2.4GHz)', 'Mua điện thoại Poco X8 Pro Max 12GB/256GB đã kích hoạt bảo hành, đổi mới 30 ngày, có trả góp 0%', 'Điện thoại', 12390000, 'Xiaomi', 2, 199, 0, '2025-08-18 21:26:26', '2026-03-29 11:43:10');

-- product_images: 64 rows
INSERT INTO product_images (id, product_id, image_url) VALUES
(1, 1, 'https://cdn2.cellphones.com.vn/media/catalog/product/h/o/honor-x8d-2_2.jpg'),
(2, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-honor-x8d_1_1.jpg'),
(3, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-honor-x8d-1_1_1.jpg'),
(4, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-honor-x8d-2_1_1.jpg'),
(5, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-honor-x8d-3_1_1.jpg'),
(6, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-honor-x8d-4_1.jpg'),
(7, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-2_2.jpg'),
(8, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-5_1.jpg'),
(9, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-3_1.jpg'),
(10, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-6_1.jpg'),
(11, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-1_2.jpg'),
(12, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-8_1.jpg'),
(13, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-9_1.jpg'),
(14, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-10_1.jpg'),
(15, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-7_1.jpg'),
(16, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-11_1.jpg'),
(17, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d_2.jpg'),
(18, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-12_1.jpg'),
(19, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-13_1.jpg'),
(20, 1, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/h/o/honor-x8d-14_1.jpg'),
(21, 1, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-honor-x8d-cu-da-kich-hoat.jpg'),
(22, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-2_2.jpg'),
(23, 1, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-honor-x8d_1_1.jpg'),
(24, 1, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-honor-x8d-1_1_1.jpg'),
(25, 1, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-honor-x8d-2_1_1.jpg'),
(26, 1, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-honor-x8d-3_1_1.jpg'),
(27, 1, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-honor-x8d-4_1.jpg'),
(28, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-5_1.jpg'),
(29, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-3_1.jpg'),
(30, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-6_1.jpg'),
(31, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-1_2.jpg'),
(32, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-8_1.jpg'),
(33, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-9_1.jpg'),
(34, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-10_1.jpg'),
(35, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-7_1.jpg'),
(36, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-11_1.jpg'),
(37, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d_2.jpg'),
(38, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-12_1.jpg'),
(39, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-13_1.jpg'),
(40, 1, 'https://cellphones.com.vn/media/catalog/product/h/o/honor-x8d-14_1.jpg'),
(41, 2, 'https://cdn2.cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max_2_1.jpg'),
(42, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max_2.jpg'),
(43, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-1_2.jpg'),
(44, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-2_2.jpg'),
(45, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-3_2.jpg'),
(46, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-4_2.jpg'),
(47, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/x/i/xiaomi-poco-x8-pro-max_2_1.jpg'),
(48, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-1_3.jpg'),
(49, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-4_2.jpg'),
(50, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-5_2.jpg'),
(51, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-2_2.jpg'),
(52, 2, 'https://cdn2.cellphones.com.vn/x/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-3_2.jpg'),
(53, 2, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-cu-da-kich-hoat.jpg'),
(54, 2, 'https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max_2_1.jpg'),
(55, 2, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max_2.jpg'),
(56, 2, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-1_2.jpg'),
(57, 2, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-2_2.jpg'),
(58, 2, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-3_2.jpg'),
(59, 2, 'https://cellphones.com.vn/media/catalog/product/d/i/dien-thoai-xiaomi-poco-x8-pro-max-4_2.jpg'),
(60, 2, 'https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-1_3.jpg'),
(61, 2, 'https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-4_2.jpg'),
(62, 2, 'https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-5_2.jpg'),
(63, 2, 'https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-2_2.jpg'),
(64, 2, 'https://cellphones.com.vn/media/catalog/product/x/i/xiaomi-poco-x8-pro-max-3_2.jpg');

-- addresses: 20 rows
INSERT INTO addresses (id, user_id, recipient_name, phone, province, district, ward, street, detail, is_default, created_at) VALUES
(1, 1, 'User1 Demo', '0900000001', 'Hà Nội', 'Quận 2', 'Phường 2', '101 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-11-05 00:09:18'),
(2, 2, 'User2 Demo', '0900000002', 'TP. Hồ Chí Minh', 'Quận 3', 'Phường 3', '102 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-07-09 16:59:31'),
(3, 3, 'User3 Demo', '0900000003', 'Đà Nẵng', 'Quận 4', 'Phường 4', '103 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-09-07 19:52:36'),
(4, 4, 'User4 Demo', '0900000004', 'Cần Thơ', 'Quận 5', 'Phường 5', '104 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2024-11-28 03:33:02'),
(5, 5, 'User5 Demo', '0900000005', 'Hải Phòng', 'Quận 6', 'Phường 6', '105 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2024-06-05 06:45:22'),
(6, 6, 'User6 Demo', '0900000006', 'Hà Nội', 'Quận 7', 'Phường 7', '106 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-02-08 18:56:17'),
(7, 7, 'User7 Demo', '0900000007', 'TP. Hồ Chí Minh', 'Quận 8', 'Phường 8', '107 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2024-04-30 14:45:45'),
(8, 8, 'User8 Demo', '0900000008', 'Đà Nẵng', 'Quận 9', 'Phường 9', '108 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2024-11-08 14:06:59'),
(9, 9, 'User9 Demo', '0900000009', 'Cần Thơ', 'Quận 10', 'Phường 10', '109 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-02-18 11:52:06'),
(10, 10, 'User10 Demo', '0900000010', 'Hải Phòng', 'Quận 11', 'Phường 11', '110 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2026-01-12 01:43:43'),
(11, 11, 'User11 Demo', '0900000011', 'Hà Nội', 'Quận 12', 'Phường 12', '111 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-07-09 18:15:06'),
(12, 12, 'User12 Demo', '0900000012', 'TP. Hồ Chí Minh', 'Quận 1', 'Phường 13', '112 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2024-09-06 12:04:37'),
(13, 13, 'User13 Demo', '0900000013', 'Đà Nẵng', 'Quận 2', 'Phường 14', '113 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-10-09 09:35:08'),
(14, 14, 'User14 Demo', '0900000014', 'Cần Thơ', 'Quận 3', 'Phường 15', '114 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2024-09-29 22:41:44'),
(15, 15, 'User15 Demo', '0900000015', 'Hải Phòng', 'Quận 4', 'Phường 16', '115 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2024-10-16 16:35:25'),
(16, 16, 'User16 Demo', '0900000016', 'Hà Nội', 'Quận 5', 'Phường 17', '116 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-04-16 20:27:58'),
(17, 17, 'User17 Demo', '0900000017', 'TP. Hồ Chí Minh', 'Quận 6', 'Phường 18', '117 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-01-02 21:00:07'),
(18, 18, 'User18 Demo', '0900000018', 'Đà Nẵng', 'Quận 7', 'Phường 19', '118 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-01-28 01:05:38'),
(19, 19, 'User19 Demo', '0900000019', 'Cần Thơ', 'Quận 8', 'Phường 20', '119 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-01-17 16:31:07'),
(20, 20, 'User20 Demo', '0900000020', 'Hải Phòng', 'Quận 9', 'Phường 1', '120 Đường Mẫu', 'Địa chỉ tạo tự động để seed dữ liệu quan hệ.', 1, '2025-12-01 00:33:58');

-- carts: 20 rows
INSERT INTO carts (id, user_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15),
(16, 16),
(17, 17),
(18, 18),
(19, 19),
(20, 20);

-- cart_items: 33 rows
INSERT INTO cart_items (id, cart_id, product_id, quantity) VALUES
(1, 1, 1, 1),
(2, 1, 2, 1),
(3, 2, 1, 1),
(4, 2, 2, 2),
(5, 3, 2, 1),
(6, 3, 1, 2),
(7, 4, 2, 2),
(8, 4, 1, 1),
(9, 5, 1, 1),
(10, 5, 2, 1),
(11, 6, 1, 1),
(12, 6, 2, 2),
(13, 7, 1, 2),
(14, 8, 2, 2),
(15, 8, 1, 2),
(16, 9, 1, 2),
(17, 9, 2, 2),
(18, 10, 2, 2),
(19, 11, 2, 2),
(20, 11, 1, 2),
(21, 12, 1, 2),
(22, 12, 2, 2),
(23, 13, 1, 1),
(24, 13, 2, 1),
(25, 14, 1, 1),
(26, 15, 1, 2),
(27, 16, 2, 2),
(28, 16, 1, 1),
(29, 17, 1, 1),
(30, 18, 1, 2),
(31, 19, 2, 2),
(32, 20, 2, 1),
(33, 20, 1, 1);

-- orders: 8 rows
INSERT INTO orders (id, user_id, total_price, status, recipient_name, phone, address, created_at) VALUES
(1, 2, 24970000, 'SHIPPED', 'User2 Demo', '0900000002', '102 Đường Mẫu, Quận 3, Đà Nẵng', '2025-02-25 20:05:44'),
(2, 4, 37360000, 'SHIPPED', 'User4 Demo', '0900000004', '104 Đường Mẫu, Quận 5, Hải Phòng', '2024-09-03 06:01:26'),
(3, 5, 24780000, 'PAID', 'User5 Demo', '0900000005', '105 Đường Mẫu, Quận 6, Hà Nội', '2026-02-19 07:11:10'),
(4, 8, 12580000, 'SHIPPED', 'User8 Demo', '0900000008', '108 Đường Mẫu, Quận 9, Cần Thơ', '2025-09-22 14:42:53'),
(5, 10, 18680000, 'PAID', 'User10 Demo', '0900000010', '110 Đường Mẫu, Quận 11, Hà Nội', '2025-10-20 09:54:58'),
(6, 15, 24970000, 'SHIPPED', 'User15 Demo', '0900000015', '115 Đường Mẫu, Quận 4, Hà Nội', '2025-03-02 11:15:30'),
(7, 16, 24970000, 'COMPLETED', 'User16 Demo', '0900000016', '116 Đường Mẫu, Quận 5, TP. Hồ Chí Minh', '2025-06-14 04:27:31'),
(8, 18, 18680000, 'PENDING', 'User18 Demo', '0900000018', '118 Đường Mẫu, Quận 7, Cần Thơ', '2025-05-14 11:50:05');

-- order_items: 14 rows
INSERT INTO order_items (id, order_id, product_id, price, quantity) VALUES
(1, 1, 2, 12390000, 1),
(2, 1, 1, 6290000, 2),
(3, 2, 2, 12390000, 2),
(4, 2, 1, 6290000, 2),
(5, 3, 2, 12390000, 2),
(6, 4, 1, 6290000, 2),
(7, 5, 1, 6290000, 1),
(8, 5, 2, 12390000, 1),
(9, 6, 1, 6290000, 2),
(10, 6, 2, 12390000, 1),
(11, 7, 1, 6290000, 2),
(12, 7, 2, 12390000, 1),
(13, 8, 2, 12390000, 1),
(14, 8, 1, 6290000, 1);

-- reviews: no rows

-- wishlists: 16 rows
INSERT INTO wishlists (user_id, product_id) VALUES
(2, 2),
(2, 1),
(4, 2),
(4, 1),
(7, 2),
(7, 1),
(8, 2),
(8, 1),
(10, 1),
(12, 2),
(12, 1),
(15, 2),
(15, 1),
(18, 1),
(18, 2),
(20, 2);

SET FOREIGN_KEY_CHECKS = 1;